(() => {
  "use strict";

  function createApi({
    canTrackByScent,
    createScentTrail,
    deleteScentTrail,
    constants,
    evaluateScentDetection,
    evaluateScentState,
    getContextApi,
    getEffectiveScentRange,
    getOdorProfile,
    getOdorProfileApi,
    getScentContext,
    getScentRange,
    getScentRules,
    getScentStateApi,
    getScentTrailDc,
    getScentTrails,
    getScentTrailsApi,
    getTrackingByScentDc,
    hasScent,
    identifyFamiliarOdor,
    isOverlayVisible,
    openContextManager,
    openTrailManager,
    refresh,
    resetNotificationState,
    rollTrackByScent,
    scan,
    setOdorProfileFlags,
    setOverlayVisible,
    setScentContextFlags,
    syncActorTokens,
    updateScentTrail,
  } = {}) {
    return {
      constants,
      context: getContextApi(),
      odorProfile: getOdorProfileApi(),
      rules: getScentRules(),
      state: getScentStateApi(),
      trails: getScentTrailsApi(),
      canTrackByScent,
      createScentTrail,
      deleteScentTrail,
      evaluateScentDetection,
      evaluateScentState,
      getEffectiveScentRange,
      getOdorProfile,
      getScentContext,
      getScentRange,
      getScentTrailDc,
      getScentTrails,
      getTrackingByScentDc,
      hasScent,
      identifyFamiliarOdor,
      isOverlayVisible,
      openContextManager,
      openTrailManager,
      refresh,
      resetNotificationState,
      rollTrackByScent,
      scan,
      setOdorProfileFlags,
      setScentContextFlags,
      setOverlayVisible,
      syncActorTokens,
      updateScentTrail,
    };
  }

  globalThis.d35eScentSenseApi = Object.freeze({
    create: createApi,
  });
})();
